name: Devpass checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Download test file
        run: curl -0 https://devpass-api-bucket.s3.amazonaws.com/testes/devpass-community/challenge-1700688203100/conditionals.test.js -o conditionals.test.js

      - name: Run unit tests
        run: yarn test
